version: '3.9'
services:
  postgres:
    build: ./postgres
    image: grindarius/postgres
    container_name: ger2-postgres-server
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.d:/docker-entrypoint-initdb.d
    ports:
      - 7321:5432
    environment:
      - POSTGRES_DB=ger2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  file-database-server:
    image: postgres:16-alpine
    container_name: ger2-file-database-server
    volumes:
      - file_server_data:/var/lib/postgresql/data
    ports:
      - 7421:5432
    environment:
      - POSTGRES_DB=ger2_file_server
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7-alpine
    container_name: ger2-redis-server
    restart: always
    command: redis-server --appendonly no
    ports:
      - 11329:6379
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  file_server_data:
  redis_data:
