services:
  postgres:
    image: groonga/pgroonga:latest-alpine-16
    container_name: ger2-postgres-server
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.d:/docker-entrypoint-initdb.d
    ports:
      - 7321:5432
    environment:
      - POSTGRES_DB=ger2
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  s3mock:
    image: adobe/s3mock
    container_name: ger2-s3-mock
    environment:
      - initialBuckets=ger2
    ports:
      - 3792:9090

  google-cloud-storage:
    image: fsouza/fake-gcs-server:latest
    container_name: ger2-gcs-mock
    ports:
      - 4443:4443
    command: [ "-scheme", "http", "-port", "4443", "-public-host", "gcs:4443" ]
    volumes:
      - ./scripts/seed/src/gcs/ger2/:/data/ger2/
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4443/storage/v1/b/"]
      interval: 5s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: ger2-keydb-server
    command: redis-server --appendonly no
    ports:
      - 11329:6379
    volumes:
      - ./keydb-data:/data

volumes:
  postgres_data:
