[package]
name = "cornflake"
description = "Simple unique number generator similar to ULID"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Bhattarapong Somwong <numbbutt34685@gmail.com>"]
homepage = "https://github.com/grindarius/ger2"
repository = "https://github.com/grindarius/ger2"

[dependencies]
thiserror = "1"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false
