[package]
name = "ger2-api"
description = "api server for the ger2 project"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Bhattarapong Somwong <numbbutt34685@gmail.com>"]
homepage = "https://github.com/grindarius/ger2"
repository = "https://github.com/grindarius/ger2"

[dependencies]
argon2 = "0.5"
aws-config = { version = "1", features = ["behavior-version-latest"] }
aws-credential-types = { version = "1", features = ["hardcoded-credentials"] }
aws-sdk-s3 = { version = "1", features = ["behavior-version-latest"] }
aws-types = "1"
axum = { version = "0.7", features = ["multipart", "macros"] }
deadpool-postgres = "0.13"
dotenvy = "0.15"
geo-types = { version = "0.7", features = ["serde"] }
once_cell = "1"
paste = "1"
postgres-from-row = "0.5"
postgres-types = { version = "0.2", features = ["derive", "serde-1", "with-time-0_3", "with-geo-types-0_7", "serde_json-1"] }
rust_decimal = { version = "1", features = ["serde-with-float", "serde-with-str", "db-tokio-postgres"] }
sea-query = { version = "0", features = ["derive", "attr", "thread-safe"] }
sea-query-postgres = { version = "0.4", features = ["with-time", "with-json", "with-rust_decimal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["serde-human-readable", "local-offset"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-time-0_3", "with-geo-types-0_7"] }
tower = "0.4"
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-bunyan-formatter = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ts-rs = "8"
ulid = { version = "1", features = ["serde"] }
utoipa = { version = "4", features = ["axum_extras", "time", "decimal", "ulid"] }
utoipa-swagger-ui = { version = "7", features = ["axum"] }
