[package]
name = "ger2-api"
description = "api server for the ger2 project"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Bhattarapong Somwong <numbbutt34685@gmail.com>"]
homepage = "https://github.com/grindarius/ger2"
repository = "https://github.com/grindarius/ger2"

[dependencies]
argon2 = "0.5"
axum = { version = "0.7", features = ["multipart", "macros"] }
deadpool-postgres = "0.14"
gcloud-sdk = { version = "0.25", features = ["google-rest-storage-v1"] }
geo-types = { version = "0.7", features = ["serde"] }
paste = "1"
postgres-from-row = "0.5"
postgres-types = { version = "0.2", features = ["derive", "serde-1", "with-time-0_3", "with-geo-types-0_7", "serde_json-1"] }
rust_decimal = { version = "1", features = ["serde-with-float", "serde-with-str", "db-tokio-postgres"] }
sea-query = { version = "0.32", features = ["derive", "thread-safe", "backend-postgres", "with-time", "with-json", "with-rust_decimal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["serde-human-readable", "local-offset"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-time-0_3", "with-geo-types-0_7"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-bunyan-formatter = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ts-rs = "10"
ulid = { version = "1", features = ["serde"] }
utoipa = { version = "5", features = ["axum_extras", "time", "decimal", "ulid"] }
utoipa-swagger-ui = { version = "8", features = ["axum"] }
