[package]
name = "ger2-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-cors = "0.6"
actix-multipart = "0.6"
actix-web = "4"
argon2 = "0.5"
deadpool-postgres = { version = "0.10", features = ["serde"] }
dotenvy = "0.15.7"
geo-types = { version = "0.7", features = ["serde"] }
once_cell = "1.18.0"
opentelemetry = { version = "0.19.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.18", features = ["rt-tokio"] }
randoid = "0.3.0"
refinery = { version = "0.8.10", features = ["tokio-postgres"] }
rust_decimal = { version = "1.30", features = ["serde-with-float", "serde-with-str", "db-tokio-postgres"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
time = { version = "0.3", features = ["serde-human-readable", "local-offset"] }
tokio-pg-mapper = "0.2"
tokio-pg-mapper-derive = "0.2"
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-time-0_3", "with-geo-types-0_7"] }
tracing = "0.1"
tracing-actix-web = { version = "0.7", features = ["opentelemetry_0_19"] }
tracing-appender = "0.2"
tracing-bunyan-formatter = "0.3"
tracing-opentelemetry = "0.19.0"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ts-rs = "6.2"
utoipa = { version = "3.4.3", features = ["actix_extras", "time", "decimal"] }
utoipa-swagger-ui = { version = "3.1.4", features = ["actix-web"] }
