[package]
name = "ger2-api"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5"
axum = { version = "0.7", features = ["multipart", "macros"] }
deadpool-postgres = "0.11"
dotenvy = "0.15"
geo-types = { version = "0.7", features = ["serde"] }
once_cell = "1"
opentelemetry = "0.21"
opentelemetry-jaeger = { version = "0.20", features = ["rt-tokio"] }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }
paste = "1"
postgres-from-row = "0.5"
postgres-types = { version = "0.2", features = ["derive", "serde-1", "with-time-0_3", "with-geo-types-0_7", "serde_json-1"] }
rust_decimal = { version = "1", features = ["serde-with-float", "serde-with-str", "db-tokio-postgres"] }
sea-query = { version = "0", features = ["derive", "attr", "thread-safe"] }
sea-query-postgres = { version = "0.4", features = ["with-time", "with-json", "with-rust_decimal"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0"
time = { version = "0.3", features = ["serde-human-readable", "local-offset"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7", features = ["with-serde_json-1", "with-time-0_3", "with-geo-types-0_7"] }
tower = "0"
tower-http = { version = "0.5", features = ["trace"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-bunyan-formatter = "0.3"
tracing-opentelemetry = "0.22"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ts-rs = "7"
ulid = { version = "1", features = ["serde"] }
utoipa = { version = "4", features = ["axum_extras", "time", "decimal", "ulid"] }
utoipa-rapidoc = { version = "2", features = ["axum"] }
utoipa-swagger-ui = { version = "4", features = ["axum"] }
