version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: ger2_lucia_postgres_server
    volumes:
      - lucia_postgres_data:/var/lib/postgresql/data
    ports:
      - 8475:5432
    environment:
      - POSTGRES_DB=ger2_lucia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7-alpine
    container_name: ger2_lucia_redis_server
    restart: always
    command: redis-server --appendonly no
    ports:
      - 6958:6379
    volumes:
      - lucia_redis_data:/var/lib/redis/data

volumes:
  lucia_postgres_data:
  lucia_redis_data:
